### ISSUE TITLE
AdaptiveDockingNode and all docking port alignment indicators incompatible with Bacon Docking System

### ISSUE THREAD

**Issue by 00Augustus00** [00Augustus00/Bugs#1]

**Comment by shadowmage45** [comment]
No logs, no info, = no fix

**Comment by shadowmage45** [comment]
If anyone can provide logs of the problem, I might be able to track down the issue;  as it stands now, I do not have time to d/l, install, and test a bunch of mods.  It is likely something simple/stupid such as a transform name, but will need more info to even begin looking at things.
