### ISSUE TITLE
USI Life Support causes autostage bug on Auriga CM

### ISSUE THREAD

**Issue by 00Augustus00** [00Augustus00/Bugs#2]
Should be fixed soon.

**Comment by shadowmage45** [comment]
Waiting on RD to approve/accept the changes, but no response in almost two weeks.  I would not hold my breath for this ever being fixed.

**Comment by shadowmage45** [comment]
RD Has apparently been working on all this in secret:

https://github.com/BobPalmer/USI-LS/issues/17

Should be fixed with the next release of USI-LS.

Closing for now, please re-open if it is still an issue in the future.
